### ISSUE TITLE
tq worker don't work

### ISSUE THREAD

**Issue by luis92arma** [codepr/tasq#1]
Traceback (most recent call last):
  File "/home/luis/Envs/EnvIupick/bin/tq", line 3, in <module>
    from tasq.cli.main import main
  File "/home/luis/Envs/EnvIupick/lib/python3.5/site-packages/tasq/__init__.py", line 6, in <module>
    from tasq.jobqueue import JobQueue
  File "/home/luis/Envs/EnvIupick/lib/python3.5/site-packages/tasq/jobqueue.py", line 14, in <module>
    from .worker import ProcessQueueWorker
  File "/home/luis/Envs/EnvIupick/lib/python3.5/site-packages/tasq/worker.py", line 44
    self._log = logging.getLogger(f'{__name__}.{self._name}')
                                                           ^
SyntaxError: invalid syntax

**Comment by codepr** [comment]
Tasq is developed against python 3.6 or higher, try it with version >= 3.6. I'll backport to < 3.6 in a while.
